export const ROUTES = {
  LANDING: '/',
  LOGIN: '/login',
  DASHBOARD: '/app/dashboard',
  PROJECTS: '/app/projects',
  PROJECT_DETAILS: '/app/projects/:projectId',
  ANOMALIES_DUPLICATES: '/app/anomalies/duplicates',
  ANOMALIES_COSTS: '/app/anomalies/costs',
  ANOMALIES_DELAYS: '/app/anomalies/delays',
  ANOMALIES_COMPLIANCE: '/app/anomalies/compliance',
  ANOMALY_DETAILS: '/app/anomalies/:anomalyId',
  ANALYTICS: '/app/analytics',
  ALERTS: '/app/alerts',
  REPORTS: '/app/reports',
  PROFILE: '/app/profile',
};
